name: churchapp
description: A Flutter application for church translation with Bluetooth connectivity.

publish_to: 'none'

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue: ^0.8.0
  audioplayers: ^0.20.1
  permission_handler: ^10.2.0
  device_preview: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/background.jpg
